// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CssGrid: typeof import('./src/components/CssGrid.vue')['default']
    Info: typeof import('./src/components/Appraisal/Info.vue')['default']
    Item: typeof import('./src/components/Appraisal/Item.vue')['default']
    List: typeof import('./src/components/Appraisal/List.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCountdown: typeof import('naive-ui')['NCountdown']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormGroup: typeof import('naive-ui')['NFormGroup']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormIyem: typeof import('naive-ui')['NFormIyem']
    NFromItem: typeof import('naive-ui')['NFromItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLable: typeof import('naive-ui')['NLable']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTimePicker: typeof import('naive-ui')['NTimePicker']
  }
}
