// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CssGrid: typeof import('./src/components/CssGrid.vue')['default']
    Info: typeof import('./src/components/Appraisal/Info.vue')['default']
    Item: typeof import('./src/components/Appraisal/Item.vue')['default']
    List: typeof import('./src/components/Appraisal/List.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NInput: typeof import('naive-ui')['NInput']
    NSpace: typeof import('naive-ui')['NSpace']
    NTimePicker: typeof import('naive-ui')['NTimePicker']
  }
}
